### PR TITLE
Fix: Token expire makes page action hava no response

### LINKED ISSUE #57: Bug point : Token expired
长时间没操作，会弹出“未授权”提示框，界面所有操作都不可行

### PR DESCRIPTION
**Pull request by lorchr**
Fix #57

### CODE REVIEW

File: discovery-platform-server/discovery-platform-starter-server/src/main/java/com/nepxion/discovery/platform/server/filter/ShiroJwtFilter.java [hunk 1]
```diff
@@ -73,6 +74,10 @@ protected boolean isAccessAllowed(ServletRequest request, ServletResponse respon
         } catch (Exception e) {
             LOG.error(ExceptionTool.getRootCauseMessage(e), e);
         }
+        if(!allowed && isAjaxRequest(WebUtils.toHttp(request))) {
```
Comment (HaojunRen) [inline discovery-platform-server/discovery-platform-starter-server/src/main/java/com/nepxion/discovery/platform/server/filter/ShiroJwtFilter.java]: 代码格式化一下

File: discovery-platform-server/discovery-platform-starter-server-ui/src/main/resources/static/layuiadmin/modules/common.js [hunk 2]
```diff
@@ -13,12 +13,14 @@ layui.define(function (e) {
     admin.DEL_QUESTION = '确定要删除所选项吗?';
     admin.DEL_SUCCESS = '所选项已全部成功删除';
     admin.ACCESS_TOKEN = "n-d-access-token";
+    admin.SESSION_STATUS = 'session-status';
```
Comment (HaojunRen) [inline discovery-platform-server/discovery-platform-starter-server-ui/src/main/resources/static/layuiadmin/modules/common.js]: session-status是header么？如果是，加个n-d-前缀吧

Comment (ZhangNingPegasus) [reply discovery-platform-server/discovery-platform-starter-server-ui/src/main/resources/static/layuiadmin/modules/common.js]: agree with DaLao Ren
